import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const CONTENT_DIR = join(__dirname, '..', 'content');
const MEMBERS_DIR = join(CONTENT_DIR, 'members');
const DINNERS_DIR = join(CONTENT_DIR, 'dinners');

mkdirSync(MEMBERS_DIR, { recursive: true });
mkdirSync(DINNERS_DIR, { recursive: true });

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

interface RawMember {
  name: string;
  title: string;
  company: string;
  bio: string;
  linkedin: string;
  twitter: string;
  website: string;
  tags: string[];
  roleType: string;
  dinners: string[];
}

// All unique members across all 12 dinners (Oct 2024 – Q1 2026)
const rawMembers: RawMember[] = [
  // ─── HOST ────────────────────────────────────────────────────────────────
  {
    name: 'Eddie Forson',
    title: 'Software Engineer & AI Consultant',
    company: 'Kiseki Labs',
    bio: 'Software engineer with experience in finance/FX, mobility startups, energy and reinsurance. Founded Kiseki Labs AI Consultancy. CTO at a reinsurance consultancy. Writes about LLMs and AI Agents on Substack.',
    linkedin: 'https://www.linkedin.com/in/eddie-forson/',
    twitter: 'https://x.com/Ed_Forson',
    website: 'https://www.kisekilabs.com/',
    tags: ['ai-agents', 'llms', 'consulting', 'startups'],
    roleType: 'engineer',
    dinners: [
      '2024-10-october', '2024-11-november', '2024-12-december',
      '2025-01-january', '2025-02-february', '2025-03-march',
      '2025-04-april', '2025-05-may', '2025-06-june',
      '2025-07-july', '2025-12-december', '2026-q1',
    ],
  },

  // ─── OCTOBER 2024 ────────────────────────────────────────────────────────
  {
    name: 'Maureen Emeagi',
    title: 'GP & Beauty Brand Founder',
    company: '',
    bio: 'General Practitioner and beauty brand founder exploring the intersection of healthcare and social media AI.',
    linkedin: 'https://www.linkedin.com/in/drmaureenemeagi/',
    twitter: '',
    website: '',
    tags: ['healthcare', 'startups'],
    roleType: 'founder',
    dinners: ['2024-10-october'],
  },
  {
    name: 'Charlie Daly',
    title: 'Software Developer',
    company: 'MixedRealityRooms',
    bio: 'Software developer building immersive mixed-reality experiences for education and collaboration.',
    linkedin: 'https://www.linkedin.com/in/charlie-daly/',
    twitter: '',
    website: '',
    tags: ['rag', 'startups', 'education'],
    roleType: 'engineer',
    dinners: ['2024-10-october'],
  },
  {
    name: 'Ollie',
    title: 'Software Engineer',
    company: '',
    bio: 'Software engineer at a crypto/NFT company building on-chain products.',
    linkedin: '',
    twitter: '',
    website: '',
    tags: ['startups'],
    roleType: 'engineer',
    dinners: ['2024-10-october'],
  },
  {
    name: 'Rodrigo Diaz',
    title: 'Head of Commercial & Digital Strategy',
    company: '',
    bio: 'Head of Commercial and Digital Strategy in the animal pharma industry, driving marketing and product innovation.',
    linkedin: 'https://www.linkedin.com/in/rodrigo-d%C3%ADaz-0411469/',
    twitter: '',
    website: '',
    tags: ['marketing', 'startups', 'product'],
    roleType: 'consultant',
    dinners: ['2024-10-october'],
  },
  {
    name: 'Kofi',
    title: 'CRM & Automation Expert',
    company: '',
    bio: 'Mechanical engineer turned CRM and automation consultant helping startups streamline operations.',
    linkedin: 'https://www.linkedin.com/in/imkofi/',
    twitter: '',
    website: '',
    tags: ['consulting', 'startups'],
    roleType: 'consultant',
    dinners: ['2024-10-october'],
  },

  // ─── NOVEMBER 2024 ───────────────────────────────────────────────────────
  {
    name: 'Ezo Saleh',
    title: 'Software Engineer & AI Startup Founder',
    company: '',
    bio: 'Software engineer and founder of an AI developer-tools startup, focused on accelerating the dev workflow with LLMs.',
    linkedin: 'https://www.linkedin.com/in/ezosaleh/',
    twitter: '',
    website: '',
    tags: ['ai-agents', 'llms', 'startups'],
    roleType: 'founder',
    dinners: ['2024-11-november'],
  },
  {
    name: 'Oren Horesh',
    title: 'Economist turned Product Manager',
    company: '',
    bio: 'Economist turned PM building an AI product for the conference and events market.',
    linkedin: 'https://www.linkedin.com/in/orenhoresh/',
    twitter: '',
    website: '',
    tags: ['product', 'startups'],
    roleType: 'founder',
    dinners: ['2024-11-november'],
  },
  {
    name: 'Dave Ganly',
    title: 'Head of Product',
    company: 'Mindguard',
    bio: 'Head of Product at Mindguard, an LLM security company protecting enterprise AI deployments.',
    linkedin: 'https://www.linkedin.com/in/daveganly/',
    twitter: '',
    website: '',
    tags: ['ai-agents', 'llms', 'product'],
    roleType: 'product-manager',
    dinners: ['2024-11-november'],
  },
  {
    name: 'Seb Ben Mbarek',
    title: 'Product-Minded Engineer & Consultant',
    company: '',
    bio: 'Product-minded software engineer working as an independent consultant on early-stage tech products.',
    linkedin: 'https://www.linkedin.com/in/benmbarek/',
    twitter: '',
    website: '',
    tags: ['consulting', 'startups'],
    roleType: 'engineer',
    dinners: ['2024-11-november'],
  },
  {
    name: 'Ben Corbett',
    title: 'Startup Founder',
    company: '',
    bio: 'Serial entrepreneur with a focus on UX, product design and AI-powered applications.',
    linkedin: 'https://www.linkedin.com/in/ben-corbett-9a634820/',
    twitter: '',
    website: '',
    tags: ['product', 'startups'],
    roleType: 'founder',
    dinners: ['2024-11-november'],
  },
  {
    name: 'Alex Glaser',
    title: 'Data Scientist',
    company: '',
    bio: 'Data scientist with experience across multiple industries including UK government, Shell Digital Ventures and AI-music side projects.',
    linkedin: 'https://www.linkedin.com/in/alexglaser1/',
    twitter: '',
    website: '',
    tags: ['data-science'],
    roleType: 'data-scientist',
    dinners: ['2024-11-november', '2025-01-january', '2025-06-june'],
  },
  {
    name: 'Jose',
    title: 'Entrepreneur & Founder',
    company: 'Hosst',
    bio: 'Entrepreneur building Hosst, an AI-powered patient home-care platform.',
    linkedin: 'https://www.linkedin.com/in/superapps/',
    twitter: '',
    website: '',
    tags: ['healthcare', 'startups'],
    roleType: 'founder',
    dinners: ['2024-11-november'],
  },

  // ─── DECEMBER 2024 ───────────────────────────────────────────────────────
  {
    name: 'Remi Bernal',
    title: 'Engineering Manager',
    company: '',
    bio: 'Software engineering manager at a hedge fund, leading AI/ML application development for financial markets.',
    linkedin: 'https://www.linkedin.com/in/remi-bernal/',
    twitter: '',
    website: '',
    tags: ['fintech', 'llms'],
    roleType: 'engineer',
    dinners: ['2024-12-december'],
  },
  {
    name: 'Fred',
    title: 'Ex-Monzo Staff Engineer & Founder',
    company: 'Tensor Valley',
    bio: 'Former Monzo Staff Engineer who founded Tensor Valley, an AI consultancy delivering production-grade ML systems.',
    linkedin: 'https://www.linkedin.com/in/enginoid/',
    twitter: '',
    website: '',
    tags: ['ai-agents', 'llms', 'consulting'],
    roleType: 'engineer',
    dinners: ['2024-12-december'],
  },
  {
    name: 'Matt Collins',
    title: 'Product-Minded CTO',
    company: '',
    bio: 'Product-minded CTO with deep expertise in web search, publishing and AI-powered content platforms.',
    linkedin: 'https://www.linkedin.com/in/mattcollinsuk/',
    twitter: '',
    website: '',
    tags: ['product', 'startups'],
    roleType: 'engineer',
    dinners: ['2024-12-december'],
  },
  {
    name: 'Matt Carey',
    title: 'AI Engineer',
    company: 'StackOne',
    bio: 'AI Engineer at StackOne specialising in AI agents and LLM integrations for HR tech.',
    linkedin: 'https://www.linkedin.com/in/mattzcarey/',
    twitter: '',
    website: '',
    tags: ['ai-agents', 'llms'],
    roleType: 'engineer',
    dinners: ['2024-12-december'],
  },
  {
    name: 'Hugh Hopkins',
    title: 'Founder',
    company: 'Delegate (acquired)',
    bio: 'Ex co-founder of Delegate, a Customer Success/Account Management startup, with a background in product management.',
    linkedin: 'https://www.linkedin.com/in/hughhopkins/',
    twitter: '',
    website: '',
    tags: ['product', 'startups'],
    roleType: 'founder',
    dinners: ['2024-12-december', '2025-04-april'],
  },

  // ─── JANUARY 2025 ────────────────────────────────────────────────────────
  {
    name: 'Dylan Loveday-Powell',
    title: 'Strategic Designer',
    company: '',
    bio: 'Strategic designer running an independent design studio at the frontier of AI-assisted creative work.',
    linkedin: 'https://www.linkedin.com/in/dylanlovedaypowell/',
    twitter: '',
    website: '',
    tags: ['creative-ai', 'product'],
    roleType: 'designer',
    dinners: ['2025-01-january'],
  },
  {
    name: 'Gabriella',
    title: 'Freelance Producer',
    company: 'Channel 4',
    bio: 'Freelance producer at Channel 4 exploring AI tools for media production and creative storytelling.',
    linkedin: 'https://www.linkedin.com/in/graeinc/',
    twitter: '',
    website: '',
    tags: ['creative-ai'],
    roleType: 'consultant',
    dinners: ['2025-01-january'],
  },
  {
    name: 'Greg Asquith',
    title: 'Software Engineer & Paid Marketing Consultant',
    company: '',
    bio: 'Software engineer who has mastered paid marketing platforms, now using LLMs and AI Agents for client automation in advertising.',
    linkedin: 'https://www.linkedin.com/in/gregasquith/',
    twitter: '',
    website: '',
    tags: ['marketing', 'ai-agents'],
    roleType: 'engineer',
    dinners: ['2025-01-january', '2025-06-june'],
  },
  {
    name: 'Pep Marti',
    title: 'Data Scientist',
    company: 'British Airways / Aer Lingus',
    bio: 'Data Scientist at British Airways and Aer Lingus applying ML to revenue management and operations in aviation and fintech.',
    linkedin: 'https://www.linkedin.com/in/pep-mart%C3%AD-mascar%C3%B3-monserrat/',
    twitter: '',
    website: '',
    tags: ['data-science', 'fintech'],
    roleType: 'data-scientist',
    dinners: ['2025-01-january'],
  },
  {
    name: 'Priyesh Sharad',
    title: 'CEO / CTO / Director',
    company: 'Roboman / Intuicon / Inkarno',
    bio: 'Data Scientist splitting time across three companies as CEO of Roboman, CTO of Intuicon, and Director of Inkarno.',
    linkedin: 'https://www.linkedin.com/in/priyesh-s-5650b672/',
    twitter: '',
    website: '',
    tags: ['ai-agents', 'data-science', 'startups'],
    roleType: 'founder',
    dinners: ['2025-01-january', '2025-05-may'],
  },

  // ─── FEBRUARY 2025 ───────────────────────────────────────────────────────
  {
    name: 'Dominic O\'Norton',
    title: 'AI & Community Consultant',
    company: '',
    bio: 'AI and Community Consultant focused on low/no-code approaches and tinkering with LLMs for commercial and social projects.',
    linkedin: 'https://www.linkedin.com/in/dominiconorton/',
    twitter: '',
    website: '',
    tags: ['llms', 'consulting', 'vibe-coding'],
    roleType: 'consultant',
    dinners: ['2025-02-february', '2025-04-april'],
  },
  {
    name: 'Elias Nema',
    title: 'Engineering Manager',
    company: 'Meta',
    bio: 'Engineering Manager at Meta working at the intersection of ML and virtual reality.',
    linkedin: 'https://www.linkedin.com/in/eliasnema/',
    twitter: '',
    website: '',
    tags: ['llms'],
    roleType: 'engineer',
    dinners: ['2025-02-february'],
  },
  {
    name: 'Folajimi Odukomaiya',
    title: 'Senior Product Manager',
    company: '',
    bio: 'Senior PM at a FinTech company and ex-Data Science EdTech founder, applying AI agents to financial products.',
    linkedin: 'https://www.linkedin.com/in/folajimi-odukomaiya/',
    twitter: '',
    website: '',
    tags: ['ai-agents', 'llms', 'fintech', 'product'],
    roleType: 'product-manager',
    dinners: ['2025-02-february'],
  },
  {
    name: 'Jordan McRae',
    title: 'Exited Founder',
    company: '',
    bio: 'Exited founder from the wearable/hardware space, exploring new startup opportunities at the frontier of AI.',
    linkedin: 'https://www.linkedin.com/in/jmcrae23/',
    twitter: '',
    website: '',
    tags: ['startups'],
    roleType: 'founder',
    dinners: ['2025-02-february'],
  },
  {
    name: 'Tiago Pina',
    title: 'Head of Engineering',
    company: '',
    bio: 'Head of Engineering at a Climate Tech startup, vibe-coding enthusiast and LLM tooling explorer.',
    linkedin: 'https://www.linkedin.com/in/tpina/',
    twitter: '',
    website: '',
    tags: ['llms', 'vibe-coding'],
    roleType: 'engineer',
    dinners: ['2025-02-february'],
  },
  {
    name: 'Timi Folaranmi',
    title: 'Data Scientist',
    company: '',
    bio: 'Data Scientist at a private equity firm who builds RAG applications and explores LLM tooling in his spare time.',
    linkedin: 'https://www.linkedin.com/in/timifolaranmi/',
    twitter: '',
    website: '',
    tags: ['rag', 'llms', 'data-science'],
    roleType: 'data-scientist',
    dinners: ['2025-02-february'],
  },

  // ─── MARCH 2025 ──────────────────────────────────────────────────────────
  {
    name: 'Nicola Croce',
    title: 'Former PM at Synthesia / ML Institute',
    company: '',
    bio: 'Former Product Manager at Synthesia with deep experience at the intersection of machine learning and AI-generated video.',
    linkedin: 'https://www.linkedin.com/in/nicocroce/',
    twitter: '',
    website: '',
    tags: ['product', 'llms'],
    roleType: 'product-manager',
    dinners: ['2025-03-march'],
  },
  {
    name: 'Louis',
    title: 'Product Manager',
    company: 'Gitpod',
    bio: 'PM at Gitpod building AI-native products, with a side project in AI for defence.',
    linkedin: 'https://www.linkedin.com/in/loujaybee/',
    twitter: '',
    website: '',
    tags: ['product', 'vibe-coding', 'startups'],
    roleType: 'product-manager',
    dinners: ['2025-03-march'],
  },
  {
    name: 'Sam Cox',
    title: 'Founder',
    company: 'Resolve247',
    bio: 'Founder of Resolve247, an AI-powered customer service platform that automates resolution workflows.',
    linkedin: 'https://www.linkedin.com/in/sam-cox-b3a61919/',
    twitter: '',
    website: '',
    tags: ['ai-agents', 'startups'],
    roleType: 'founder',
    dinners: ['2025-03-march'],
  },

  // ─── APRIL 2025 (Beehiiv) ────────────────────────────────────────────────
  {
    name: 'Christina Banjo',
    title: 'Founder',
    company: 'Always Create',
    bio: 'Founder of Always Create, a community platform connecting creative freelancers with job opportunities through AI-powered matchmaking.',
    linkedin: 'https://www.linkedin.com/in/cbanjo/',
    twitter: '',
    website: '',
    tags: ['creative-ai', 'startups'],
    roleType: 'founder',
    dinners: ['2025-04-april'],
  },
  {
    name: 'Dexter Awoyemi',
    title: 'AI Consultant',
    company: '',
    bio: '10+ years in startups and scaleups with extensive Open Banking experience. Now specialising in knowledge engineering, Graph RAG and enterprise AI strategy.',
    linkedin: 'https://www.linkedin.com/in/dexterawoyemi/',
    twitter: '',
    website: '',
    tags: ['rag', 'consulting', 'startups'],
    roleType: 'consultant',
    dinners: ['2025-04-april', '2025-07-july', '2025-12-december'],
  },
  {
    name: 'Markus Duecker',
    title: 'Co-founder',
    company: 'Talentspace',
    bio: 'Co-founder of Talentspace, now focused on data labelling services for AI companies. Based in Germany with events-tech background.',
    linkedin: 'https://www.linkedin.com/in/markus-duecker/',
    twitter: '',
    website: '',
    tags: ['startups', 'data-science'],
    roleType: 'founder',
    dinners: ['2025-04-april'],
  },
  {
    name: 'Mawuli Agamah',
    title: 'Data Scientist',
    company: 'UK Dept for Business and Trade',
    bio: 'Data Scientist at the UK Department for Business and Trade with an Economics background, building a mobile app using multi-modal AI.',
    linkedin: 'https://www.linkedin.com/in/mawuliagamah/',
    twitter: '',
    website: '',
    tags: ['data-science'],
    roleType: 'data-scientist',
    dinners: ['2025-04-april'],
  },
  {
    name: 'Pyry Takala',
    title: 'Co-founder & CTO',
    company: '',
    bio: 'Co-founder and CTO of a FinTech startup in the Netherlands. Background in Data Science and ML, previously based in London.',
    linkedin: 'https://www.linkedin.com/in/pyrytakala/',
    twitter: '',
    website: '',
    tags: ['fintech', 'data-science', 'startups'],
    roleType: 'founder',
    dinners: ['2025-04-april'],
  },

  // ─── MAY 2025 (Beehiiv) ──────────────────────────────────────────────────
  {
    name: 'David Hasovic',
    title: 'Founder',
    company: 'Superthread',
    bio: 'Founder of Superthread, a modern AI-powered issue tracker. Background in video games development.',
    linkedin: 'https://www.linkedin.com/in/david-hasovic-72444539/',
    twitter: '',
    website: '',
    tags: ['ai-agents', 'startups'],
    roleType: 'founder',
    dinners: ['2025-05-may'],
  },
  {
    name: 'Farhath Razzaque',
    title: 'Full-Stack Engineer & CTO',
    company: 'King Of the Hill',
    bio: 'Full-stack and AI engineer, CTO of King Of the Hill (extreme snow sports app). Previously freelance software and AI engineering; working on an AI media project.',
    linkedin: 'https://www.linkedin.com/in/farhath-razzaque/',
    twitter: '',
    website: '',
    tags: ['creative-ai', 'startups'],
    roleType: 'engineer',
    dinners: ['2025-05-may', '2026-q1'],
  },
  {
    name: 'Kumell Rizvi',
    title: 'Optometrist & AI Tinkerer',
    company: '',
    bio: 'Optometrist dabbling with LLMs to automate the triaging of patient calls and improve clinical workflows.',
    linkedin: 'https://www.linkedin.com/in/kumell-rizvi-1522121a0/',
    twitter: '',
    website: '',
    tags: ['healthcare', 'llms'],
    roleType: 'consultant',
    dinners: ['2025-05-may'],
  },
  {
    name: 'Peter Grillet',
    title: 'Operations Consultant & Founder',
    company: 'Lnks.to',
    bio: 'Operations Consultant and Founder of Lnks.to with broad skills across tech, marketing, finance and business operations.',
    linkedin: 'https://www.linkedin.com/in/mrgrillet/',
    twitter: '',
    website: '',
    tags: ['marketing', 'consulting', 'startups'],
    roleType: 'consultant',
    dinners: ['2025-05-may'],
  },
  {
    name: 'Rene Muhire',
    title: 'Product Manager & CTO (non-profit)',
    company: 'Legal Aid Agency / Professors Without Borders',
    bio: 'PM consultant spearheading AI Agent development. CTO at Professors Without Borders. Co-organiser of the London HuggingFace Meetup.',
    linkedin: 'https://www.linkedin.com/in/irenemuhire/',
    twitter: '',
    website: '',
    tags: ['ai-agents', 'product'],
    roleType: 'product-manager',
    dinners: ['2025-05-may', '2025-06-june', '2026-q1'],
  },
  {
    name: 'Rockman Law',
    title: 'Investor',
    company: 'Merantix Capital',
    bio: 'Investor at Merantix Capital backing European AI startups. Previously founded a cyber-security startup.',
    linkedin: 'https://www.linkedin.com/in/rockmanlaw/',
    twitter: '',
    website: '',
    tags: ['startups', 'consulting'],
    roleType: 'investor',
    dinners: ['2025-05-may'],
  },
  {
    name: 'William Jones',
    title: 'CTO & Co-founder',
    company: 'Sano Genetics',
    bio: 'CTO and Co-founder of Sano Genetics with a Computer Science and Computational Biology background, applying AI to genomics.',
    linkedin: 'https://www.linkedin.com/in/willgdjones/',
    twitter: '',
    website: '',
    tags: ['ai-agents', 'startups', 'data-science'],
    roleType: 'founder',
    dinners: ['2025-05-may'],
  },

  // ─── JUNE 2025 (Beehiiv) ─────────────────────────────────────────────────
  {
    name: 'Jairo Diaz',
    title: 'Founder & Software Engineer',
    company: '',
    bio: '15-year software consultancy veteran now building a food tech startup powered by voice AI.',
    linkedin: 'https://www.linkedin.com/in/jairodiaz4/',
    twitter: '',
    website: '',
    tags: ['ai-agents', 'startups'],
    roleType: 'founder',
    dinners: ['2025-06-june'],
  },
  {
    name: 'Liberatus',
    title: 'Senior Product Manager',
    company: 'Amazon / Reps app',
    bio: 'Senior PM at Amazon for ML-driven EU-wide logistics. PM at an AI-native agency building Reps. Vibe-coding enthusiast.',
    linkedin: 'https://www.linkedin.com/in/liberatus/',
    twitter: '',
    website: '',
    tags: ['product', 'startups', 'vibe-coding'],
    roleType: 'product-manager',
    dinners: ['2025-06-june', '2026-q1'],
  },
  {
    name: 'Oliver Short',
    title: 'Founder',
    company: 'SEEKR',
    bio: 'Founder of SEEKR, a tech recruitment company connecting AI engineers with hiring companies.',
    linkedin: 'https://www.linkedin.com/in/olivershort/',
    twitter: '',
    website: '',
    tags: ['startups'],
    roleType: 'founder',
    dinners: ['2025-06-june'],
  },
  {
    name: 'Olivier Legris',
    title: 'Co-founder',
    company: 'Alter',
    bio: 'Co-founder of Alter, an AI assistant for Mac. Background in UX, Marketing and Product with a focus on model routing.',
    linkedin: 'https://www.linkedin.com/in/legris/',
    twitter: '',
    website: '',
    tags: ['product', 'startups'],
    roleType: 'founder',
    dinners: ['2025-06-june'],
  },
  {
    name: 'Roberta Goodhead',
    title: 'Senior Software Engineer',
    company: 'VodafoneThree',
    bio: 'Senior Software Engineer at VodafoneThree. Imperial alumna with experience in healthcare and telecoms and a keen interest in generative AI.',
    linkedin: 'https://www.linkedin.com/in/robertagoodhead/',
    twitter: '',
    website: '',
    tags: ['llms', 'vibe-coding'],
    roleType: 'engineer',
    dinners: ['2025-06-june', '2025-07-july'],
  },
  {
    name: 'Xavier Akram',
    title: 'Founder',
    company: 'TokenHouse Capital',
    bio: 'Founder of TokenHouse Capital, an investment firm operating in the UK, China and Middle East, actively testing AI models for investment research.',
    linkedin: 'https://www.linkedin.com/in/xavierakram/',
    twitter: '',
    website: '',
    tags: ['fintech', 'startups'],
    roleType: 'investor',
    dinners: ['2025-06-june'],
  },

  // ─── JULY 2025 (Beehiiv) ─────────────────────────────────────────────────
  {
    name: 'Abrar Rashid',
    title: 'MEng Computing Graduate',
    company: 'Imperial College London',
    bio: 'MEng Computing graduate from Imperial working on KidneyGrader, a deep learning system for kidney biopsy grading.',
    linkedin: 'https://www.linkedin.com/in/abrar-rashid/',
    twitter: '',
    website: '',
    tags: ['healthcare', 'startups', 'data-science'],
    roleType: 'engineer',
    dinners: ['2025-07-july'],
  },
  {
    name: 'Gabi Teodoru',
    title: 'AI Engineer',
    company: '',
    bio: 'AI Engineer with a quantitative trading background, teaching AI to write q (kdb+) language for time-series financial data.',
    linkedin: 'https://www.linkedin.com/in/gabiteodoru/',
    twitter: '',
    website: '',
    tags: ['fintech', 'llms'],
    roleType: 'engineer',
    dinners: ['2025-07-july'],
  },
  {
    name: 'Harvey Yorke',
    title: 'Co-founder & CTO',
    company: 'Valyu',
    bio: 'Co-founder and CTO of Valyu, building multimodal search APIs for AI Agents. UCL graduate with AI research background.',
    linkedin: 'https://www.linkedin.com/in/harveyyorke/',
    twitter: '',
    website: '',
    tags: ['rag', 'ai-agents', 'startups'],
    roleType: 'founder',
    dinners: ['2025-07-july'],
  },
  {
    name: 'Kitan Ogunfeibo',
    title: 'Founder, Growth Consultancy',
    company: '',
    bio: 'Founder of a growth consultancy specialising in digital strategy for MedTech companies including Flow Health and Health Words AI.',
    linkedin: 'https://www.linkedin.com/in/kitan-ogunfeibo/',
    twitter: '',
    website: '',
    tags: ['marketing', 'healthcare', 'startups'],
    roleType: 'founder',
    dinners: ['2025-07-july', '2025-12-december'],
  },
  {
    name: 'Rachel Blondon',
    title: 'Ex-Founder & AI Builder',
    company: '',
    bio: 'Developer turned DevRel and AI builder. Ex-crypto founder who now runs a popular AI building meetup.',
    linkedin: 'https://www.linkedin.com/in/rachblondon/',
    twitter: '',
    website: '',
    tags: ['ai-agents', 'startups', 'vibe-coding'],
    roleType: 'founder',
    dinners: ['2025-07-july'],
  },
  {
    name: 'Shingi Mureriwa',
    title: 'Former Director, Financial Risk Management',
    company: '',
    bio: 'Former Financial Risk Management Director at Barclays, HSBC and Nordea. Now building a personal AI trading system.',
    linkedin: 'https://www.linkedin.com/in/shingi-mureriwa-2a602b31/',
    twitter: '',
    website: '',
    tags: ['fintech', 'llms'],
    roleType: 'consultant',
    dinners: ['2025-07-july'],
  },
  {
    name: 'Simon',
    title: 'Founder',
    company: 'TheEndOfConflict.ai',
    bio: '20 years of teaching negotiation and author of "The End of Conflict". Building an AI platform for conflict resolution.',
    linkedin: '',
    twitter: '',
    website: '',
    tags: ['ai-agents', 'startups'],
    roleType: 'founder',
    dinners: ['2025-07-july'],
  },

  // ─── DECEMBER 2025 (Beehiiv) ─────────────────────────────────────────────
  {
    name: 'David Farrell',
    title: 'Software/AI Consultant & Former Lecturer',
    company: '',
    bio: 'Computer scientist, fast.ai graduate and early ChatGPT adopter. Former university lecturer now teaching AI usage as a consultant and educator.',
    linkedin: 'https://www.linkedin.com/in/davidfarrell81/',
    twitter: '',
    website: '',
    tags: ['education', 'rag', 'consulting'],
    roleType: 'consultant',
    dinners: ['2025-12-december', '2026-q1'],
  },
  {
    name: 'Dilini K Sumanapala',
    title: 'AI Contractor / Consultant / DevRel',
    company: '',
    bio: 'Built biotech chatbots and created a LangGraph Agents course for DataCamp. Active in AI DevRel and agent tooling.',
    linkedin: 'https://www.linkedin.com/in/dilini-k-sumanapala-phd/',
    twitter: '',
    website: '',
    tags: ['ai-agents', 'llms', 'consulting'],
    roleType: 'consultant',
    dinners: ['2025-12-december'],
  },
  {
    name: 'Gaurav Pooniwala',
    title: 'Independent AI Engineer',
    company: '',
    bio: '10 years in neural networks across Samsung and an Adobe acquisition. LBS MBA graduate now working independently on AI engineering.',
    linkedin: 'https://www.linkedin.com/in/gaurav-pooniwala/',
    twitter: '',
    website: '',
    tags: ['llms', 'data-science'],
    roleType: 'engineer',
    dinners: ['2025-12-december'],
  },
  {
    name: 'Ian Ozsvald',
    title: 'AI & Robotics Expert / Author / Community Leader',
    company: '',
    bio: '25 years in AI. Author of "High Performance Python". Co-founded PyData London (16K+ members). Expert in AI strategy and ARC-AGI challenges.',
    linkedin: 'https://www.linkedin.com/in/ianozsvald/',
    twitter: '',
    website: '',
    tags: ['data-science', 'consulting'],
    roleType: 'consultant',
    dinners: ['2025-12-december'],
  },
  {
    name: 'Joel Miller',
    title: 'Co-founder',
    company: 'ExoBrain',
    bio: 'Co-founder of ExoBrain. Financial services background from Accenture and Deloitte, now focused on AI adoption in the enterprise.',
    linkedin: 'https://www.linkedin.com/in/joelgmiller/',
    twitter: '',
    website: '',
    tags: ['consulting', 'startups'],
    roleType: 'founder',
    dinners: ['2025-12-december'],
  },
  {
    name: 'Joost de Jonge',
    title: 'Non-technical Co-founder',
    company: 'ExoBrain',
    bio: 'Non-technical Co-founder of ExoBrain, specialising in AI for knowledge work and disrupting the consultancy model.',
    linkedin: 'https://www.linkedin.com/in/joostdejonge/',
    twitter: '',
    website: '',
    tags: ['consulting', 'startups'],
    roleType: 'founder',
    dinners: ['2025-12-december'],
  },

  // ─── Q1 2026 ─────────────────────────────────────────────────────────────
  {
    name: 'Bode Ogunlana',
    title: 'CTO',
    company: 'Stears',
    bio: 'CTO at Stears, an African data intelligence company, building fintech and data products powered by LLMs.',
    linkedin: 'https://www.linkedin.com/in/foluso-olabode-bode-ogunlana-124522a4/',
    twitter: '',
    website: '',
    tags: ['fintech', 'llms', 'product'],
    roleType: 'engineer',
    dinners: ['2026-q1'],
  },
  {
    name: 'Neil Cameron',
    title: 'Founder',
    company: 'Response Hub',
    bio: 'Building Response Hub. Ex-CTO at Progression. Focused on AI-powered communication and product tools.',
    linkedin: 'https://www.linkedin.com/in/neiljcameron/',
    twitter: '',
    website: '',
    tags: ['startups', 'product'],
    roleType: 'founder',
    dinners: ['2026-q1'],
  },
];

// ─── DINNERS ─────────────────────────────────────────────────────────────────

interface RawDinner {
  name: string;
  slug: string;
  date: string;
  venue: string;
  description: string;
  topics: { text: string; attribution: string; links: string[] }[];
  attendees: string[]; // member slugs
  beehiivUrl: string;
  discordUrl: string;
  lumaUrl: string;
}

const rawDinners: RawDinner[] = [
  {
    name: 'October 2024 Dinner',
    slug: '2024-10-october',
    date: '2024-10-09',
    venue: 'London',
    description: 'The inaugural AI Mavericks dinner bringing together builders, founders and consultants working on AI.',
    topics: [
      { text: 'Healthcare AI and social media applications', attribution: 'Maureen', links: [] },
      { text: 'Mixed reality and RAG for education', attribution: 'Charlie', links: [] },
      { text: 'AI in animal pharma and digital strategy', attribution: 'Rodrigo', links: [] },
    ],
    attendees: ['maureen-emeagi', 'charlie-daly', 'ollie', 'rodrigo-diaz', 'kofi', 'eddie-forson'],
    beehiivUrl: '',
    discordUrl: 'https://discord.gg/xTxksjUvnE',
    lumaUrl: '',
  },
  {
    name: 'November 2024 Dinner',
    slug: '2024-11-november',
    date: '2024-11-18',
    venue: 'London',
    description: 'An evening of wide-ranging discussion on AI dev tools, LLM security and the future of AI startups.',
    topics: [
      { text: 'AI developer tools and startup building', attribution: 'Ezo', links: [] },
      { text: 'LLM security in enterprise', attribution: 'Dave', links: [] },
      { text: 'AI for the conference market', attribution: 'Oren', links: [] },
      { text: 'Patient home care automation', attribution: 'Jose', links: [] },
    ],
    attendees: ['ezo-saleh', 'oren-horesh', 'dave-ganly', 'seb-ben-mbarek', 'ben-corbett', 'alex-glaser', 'jose', 'eddie-forson'],
    beehiivUrl: '',
    discordUrl: 'https://discord.gg/xTxksjUvnE',
    lumaUrl: '',
  },
  {
    name: 'December 2024 Dinner',
    slug: '2024-12-december',
    date: '2024-12-16',
    venue: 'London',
    description: 'Year-end dinner exploring AI engineering, fintech applications and the consultant-founder divide.',
    topics: [
      { text: 'AI/ML applications in hedge funds', attribution: 'Remi', links: [] },
      { text: 'Building an AI consultancy post big-tech', attribution: 'Fred', links: [] },
      { text: 'AI agents for customer success', attribution: 'Hugh', links: [] },
    ],
    attendees: ['remi-bernal', 'fred', 'matt-collins', 'matt-carey', 'hugh-hopkins', 'eddie-forson'],
    beehiivUrl: '',
    discordUrl: 'https://discord.gg/xTxksjUvnE',
    lumaUrl: '',
  },
  {
    name: 'January 2025 Dinner',
    slug: '2025-01-january',
    date: '2025-01-30',
    venue: 'London',
    description: 'New year kickoff with designers, data scientists and marketers converging on AI\'s creative and analytical frontiers.',
    topics: [
      { text: 'AI-assisted strategic design and creative tooling', attribution: 'Dylan', links: [] },
      { text: 'Data science at scale in aviation', attribution: 'Pep', links: [] },
      { text: 'Multi-company AI leadership', attribution: 'Priyesh', links: [] },
      { text: 'LLM automation for paid marketing', attribution: 'Greg', links: [] },
    ],
    attendees: ['alex-glaser', 'dylan-loveday-powell', 'gabriella', 'greg-asquith', 'pep-marti', 'priyesh-sharad', 'eddie-forson'],
    beehiivUrl: '',
    discordUrl: 'https://discord.gg/xTxksjUvnE',
    lumaUrl: '',
  },
  {
    name: 'February 2025 Dinner',
    slug: '2025-02-february',
    date: '2025-02-24',
    venue: 'London',
    description: 'Conversations spanning FinTech PM perspectives, ML at Meta, climate tech engineering and RAG applications.',
    topics: [
      { text: 'AI agents in FinTech product management', attribution: 'Folajimi', links: [] },
      { text: 'ML and VR at Meta', attribution: 'Elias', links: [] },
      { text: 'Climate tech and vibe coding', attribution: 'Tiago', links: [] },
      { text: 'RAG apps and LLM tooling for PE firms', attribution: 'Timi', links: [] },
    ],
    attendees: ['dominic-o-norton', 'elias-nema', 'folajimi-odukomaiya', 'jordan-mcrae', 'tiago-pina', 'timi-folaranmi', 'eddie-forson'],
    beehiivUrl: '',
    discordUrl: 'https://discord.gg/xTxksjUvnE',
    lumaUrl: '',
  },
  {
    name: 'March 2025 Dinner',
    slug: '2025-03-march',
    date: '2025-03-03',
    venue: 'London',
    description: 'A focused dinner on AI product strategy, defence applications and AI-powered customer service.',
    topics: [
      { text: 'AI product strategy post-Synthesia', attribution: 'Nicola', links: [] },
      { text: 'AI for defence and vibe coding with Gitpod', attribution: 'Louis', links: [] },
      { text: 'AI-automated customer service resolution', attribution: 'Sam', links: [] },
    ],
    attendees: ['nicola-croce', 'louis', 'sam-cox', 'eddie-forson'],
    beehiivUrl: '',
    discordUrl: 'https://discord.gg/xTxksjUvnE',
    lumaUrl: '',
  },
  {
    name: 'April 2025 Dinner',
    slug: '2025-04-april',
    date: '2025-04-14',
    venue: 'London',
    description: 'Lively discussion on market selection, vibe coding and data labelling — the first Beehiiv-era dinner.',
    topics: [
      { text: 'Choosing a big enough market — Marc Andreessen\'s post on team vs product vs market', attribution: 'Hugh', links: [] },
      { text: 'Vibe coding with Replit Agent — web games built end-to-end with prompts', attribution: 'Dominic', links: ['https://replit.com/'] },
      { text: 'Professional social networks — Happenstance.ai mentioned', attribution: 'Group', links: ['https://happenstance.ai/'] },
      { text: 'Data labelling for AI — Scale.ai as the leading company', attribution: 'Markus', links: ['https://scale.com/'] },
      { text: 'UI prototyping with magicpatterns.com', attribution: 'Dominic', links: ['https://www.magicpatterns.com/'] },
    ],
    attendees: ['christina-banjo', 'dexter-awoyemi', 'dominic-o-norton', 'markus-duecker', 'mawuli-agamah', 'hugh-hopkins', 'pyry-takala', 'eddie-forson'],
    beehiivUrl: 'https://ai-mavericks-ldn.beehiiv.com/p/ai-mavericks-april-2025-dinner-recap',
    discordUrl: 'https://discord.gg/xTxksjUvnE',
    lumaUrl: '',
  },
  {
    name: 'May 2025 Dinner',
    slug: '2025-05-may',
    date: '2025-05-19',
    venue: 'London',
    description: 'Deep dive into mobile gaming economics, human connection in AI sales and technical co-founding.',
    topics: [
      { text: 'Mobile games as money makers — Candy Crush financials', attribution: 'David', links: [] },
      { text: 'Human connection in sales — Salesforce hiring 2K+ to sell AI', attribution: 'Group', links: [] },
      { text: 'EWOR accelerator — potential "YC of Europe"', attribution: 'Rockman, Farhath', links: ['https://ewor.io/'] },
      { text: 'Financial health and Customer Acquisition Cost', attribution: 'Peter', links: [] },
      { text: 'Technical co-founders still critical', attribution: 'Rockman, William', links: [] },
      { text: 'Ex-Palantir founders crushing it', attribution: 'Group', links: [] },
      { text: 'Pydantic AI for codebase rewriting', attribution: 'William / Sano Genetics', links: ['https://docs.pydantic.dev/latest/concepts/pydantic_ai/'] },
    ],
    attendees: ['david-hasovic', 'farhath-razzaque', 'kumell-rizvi', 'peter-grillet', 'priyesh-sharad', 'rene-muhire', 'rockman-law', 'william-jones', 'eddie-forson'],
    beehiivUrl: 'https://ai-mavericks-ldn.beehiiv.com/p/ai-mavericks-may-2025-dinner-recap',
    discordUrl: 'https://discord.gg/xTxksjUvnE',
    lumaUrl: '',
  },
  {
    name: 'June 2025 Dinner',
    slug: '2025-06-june',
    date: '2025-06-09',
    venue: 'London',
    description: 'Evening exploring AI model routing, the UK job market and startup MRR reporting — with returning faces.',
    topics: [
      { text: 'Mary Meeker\'s AI Report — subsidised AI and model cost decreases', attribution: 'Olivier, Rene', links: [] },
      { text: 'UK job market tough — but top AI talent getting $100M+ offers', attribution: 'Oliver', links: [] },
      { text: 'Model routing challenges and OpenRouter interest', attribution: 'Olivier / Alter', links: ['https://openrouter.ai/'] },
      { text: 'Pipedream for API integrations', attribution: 'Olivier', links: ['https://pipedream.com/'] },
      { text: 'Google Labs for AI experimentation', attribution: 'Xavier', links: [] },
      { text: 'Startup MRR/ARR reporting toxicity — Replit $10M to $100M ARR', attribution: 'Liberatus, Rene, Olivier, Eddie', links: [] },
      { text: 'LangGraph for marketing agents', attribution: 'Greg', links: ['https://www.langchain.com/langgraph'] },
      { text: 'Interview process in the AI age — allowing AI but requiring understanding', attribution: 'Eddie, Alex, Roberta, Oliver', links: [] },
    ],
    attendees: ['alex-glaser', 'greg-asquith', 'jairo-diaz', 'liberatus', 'oliver-short', 'olivier-legris', 'rene-muhire', 'roberta-goodhead', 'xavier-akram', 'eddie-forson'],
    beehiivUrl: 'https://ai-mavericks-ldn.beehiiv.com/p/ai-mavericks-june-2025-dinner-recap',
    discordUrl: 'https://discord.gg/xTxksjUvnE',
    lumaUrl: '',
  },
  {
    name: 'July 2025 Dinner',
    slug: '2025-07-july',
    date: '2025-07-14',
    venue: 'Ramen Space',
    description: 'A packed evening at Ramen Space on vibe coding tools, evolving tech roles and AI eating software.',
    topics: [
      { text: 'Vibe Coding — Lovable demo; "last mile problem"; PRDs are critical', attribution: 'Rachel, Roberta', links: ['https://lovable.dev/'] },
      { text: 'AI Tools — Claude Code vs Cursor; multi-agent workflows; Roo Code, tldraw, Vercel v0', attribution: 'Group', links: ['https://claude.ai/code'] },
      { text: 'AI is Eating Software — throwaway software; distribution still key; junior engineers must go AI native', attribution: 'Group', links: [] },
      { text: 'Legacy Languages and AI — q language (Gabi), MUMPS (Simon); COBOL/Fortran migration via bloop.ai', attribution: 'Gabi, Simon', links: [] },
      { text: 'Evolving Tech Roles — smaller teams; dev/PM/designer coalescence; "vibe designing" with MCP servers', attribution: 'Group', links: [] },
      { text: 'AI in the Enterprise — internal use cases beat customer-facing chatbots; expert systems still valuable', attribution: 'Group', links: [] },
      { text: 'Startup/Founder Insights — distribution > product (Justin Kan); founder-led sales; domain expertise', attribution: 'Group', links: [] },
      { text: 'Recommended Reading — "AI 2027", "Situational Awareness: The Decade Ahead"', attribution: 'Group', links: [] },
    ],
    attendees: ['abrar-rashid', 'dexter-awoyemi', 'gabi-teodoru', 'harvey-yorke', 'kitan-ogunfeibo', 'rachel-blondon', 'roberta-goodhead', 'shingi-mureriwa', 'simon', 'eddie-forson'],
    beehiivUrl: 'https://ai-mavericks-ldn.beehiiv.com/p/ai-mavericks-july-2025-dinner-recap',
    discordUrl: 'https://discord.gg/xTxksjUvnE',
    lumaUrl: '',
  },
  {
    name: 'December 2025 Dinner',
    slug: '2025-12-december',
    date: '2025-12-15',
    venue: 'Pizza Express Live Holborn',
    description: 'Year-end reflections on AI consulting models, economic impact of AI and the rise of robotics.',
    topics: [
      { text: 'AI Consulting models — 80/20 rule, cloud vs local deployment; bigger projects in 2026', attribution: 'Kitan, Joel', links: [] },
      { text: 'Economic Impact of AI — capitalism, inequality, automation; "AI 2027" reading', attribution: 'Group', links: [] },
      { text: 'Rise of Robotics — elderly care, healthcare, manufacturing pressures', attribution: 'Kitan', links: [] },
      { text: 'Expert Systems vs LLMs — chess at 3,500 Elo vs LLMs at 800; right tool for the job', attribution: 'Ian', links: [] },
      { text: 'AI-Generated Code challenges — duplication; need strong foundations; MCP + Figma', attribution: 'Gaurav, David', links: [] },
      { text: 'Medical Transcription — human review augmentation and terminology errors', attribution: 'Gaurav', links: [] },
      { text: 'Deep Research and News — parallel agents for synthesis; ESG signals 300% gain', attribution: 'Eddie, David', links: [] },
      { text: 'ARC-AGI and Playgroup — Ian\'s deep-dive events; ARC-AGI 2026 spatial reasoning challenge', attribution: 'Ian', links: [] },
    ],
    attendees: ['david-farrell', 'dexter-awoyemi', 'dilini-k-sumanapala', 'gaurav-pooniwala', 'ian-ozsvald', 'joel-miller', 'joost-de-jonge', 'kitan-ogunfeibo', 'eddie-forson'],
    beehiivUrl: 'https://ai-mavericks-ldn.beehiiv.com/p/ai-mavericks-december-2025-dinner-recap',
    discordUrl: 'https://discord.gg/xTxksjUvnE',
    lumaUrl: '',
  },
  {
    name: 'Q1 2026 Dinner',
    slug: '2026-q1',
    date: '2026-03-04',
    venue: 'Pizza Express Live Holborn',
    description: 'The first AI Mavericks dinner of 2026, reflecting on AI tooling, education, and the road ahead.',
    topics: [
      { text: 'Should junior developers bother learning traditional coding?', attribution: 'Group', links: [] },
      { text: 'AI in education and teaching AI usage', attribution: 'David', links: [] },
      { text: 'Building AI products for defence and creative media', attribution: 'Farhath', links: [] },
      { text: 'LLMs in African fintech data intelligence', attribution: 'Bode', links: [] },
    ],
    attendees: ['bode-ogunlana', 'david-farrell', 'farhath-razzaque', 'liberatus', 'neil-cameron', 'rene-muhire', 'eddie-forson'],
    beehiivUrl: 'https://ai-mavericks-ldn.beehiiv.com/p/ai-mavericks-q1-2026-dinner-recap',
    discordUrl: 'https://discord.gg/xTxksjUvnE',
    lumaUrl: '',
  },
];

// ─── WRITE FILES ──────────────────────────────────────────────────────────────

// Write member files
for (const raw of rawMembers) {
  const slug = slugify(raw.name);
  const member = {
    name: raw.name,
    slug,
    title: raw.title,
    company: raw.company,
    bio: raw.bio,
    photo: `/images/members/${slug}.svg`,
    linkedin: raw.linkedin,
    twitter: raw.twitter || '',
    website: raw.website || '',
    tags: raw.tags,
    roleType: raw.roleType,
    dinners: raw.dinners,
  };
  writeFileSync(
    join(MEMBERS_DIR, `${slug}.json`),
    JSON.stringify(member, null, 2) + '\n'
  );
}

// Write dinner files
for (const raw of rawDinners) {
  const dinner = {
    name: raw.name,
    slug: raw.slug,
    date: raw.date,
    venue: raw.venue,
    groupPhoto: `/images/dinners/${raw.slug}.jpg`,
    description: raw.description,
    topics: raw.topics,
    attendees: raw.attendees,
    beehiivUrl: raw.beehiivUrl,
    discordUrl: raw.discordUrl,
    lumaUrl: raw.lumaUrl,
  };
  writeFileSync(
    join(DINNERS_DIR, `${raw.slug}.json`),
    JSON.stringify(dinner, null, 2) + '\n'
  );
}

console.log(`Created ${rawMembers.length} member files and ${rawDinners.length} dinner files.`);
